# Generated by Django 4.2.5 on 2023-10-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-created_date",),},
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Replay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "which_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.comments"
                    ),
                ),
            ],
            options={"ordering": ("-created_date",),},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content1", models.TextField()),
                ("content2", models.TextField()),
                ("content3", models.TextField()),
                ("content4", models.TextField()),
                ("content5", models.TextField()),
                ("endcontent", models.TextField()),
                ("banner", models.TextField(max_length=255)),
                ("topic1", models.TextField(max_length=255)),
                ("topic2", models.TextField()),
                ("counted_views", models.IntegerField(default=0)),
                ("counted_comment", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("image", models.ImageField(default="default.jpg", upload_to="blog")),
                (
                    "second_image",
                    models.ImageField(default="blog-2.jpg", upload_to="blog"),
                ),
                (
                    "auther_img",
                    models.ImageField(default="bauth.jpg", upload_to="blog"),
                ),
                ("auther_bio", models.TextField()),
                ("twitter", models.CharField(default="twitter.com", max_length=255)),
                ("facebook", models.CharField(default="facebook.com", max_length=255)),
                (
                    "instagram",
                    models.CharField(default="instagram.com", max_length=255),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("published_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("category", models.ManyToManyField(to="blogs.category")),
                ("tag", models.ManyToManyField(to="blogs.tags")),
            ],
            options={"ordering": ("-created_date",),},
        ),
        migrations.AddField(
            model_name="comments",
            name="which_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blogs.post"
            ),
        ),
    ]
