# Generated by Django 4.2.5 on 2023-10-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="replay", name="name",),
    ]
