# Generated by Django 4.2.5 on 2023-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-created_date"],},
        ),
        migrations.CreateModel(
            name="PortFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="default.jpg", upload_to="port")),
                ("title", models.CharField(max_length=40)),
                ("ouner_name", models.CharField(default="ouner", max_length=60)),
                ("content", models.TextField(max_length=100)),
                (
                    "ouner_image",
                    models.ImageField(default="default.jpg", upload_to="port"),
                ),
                ("description", models.TextField()),
                ("client", models.TextField()),
                ("project_date", models.DateTimeField(auto_now_add=True)),
                ("project_url", models.URLField()),
                ("subject", models.CharField(default="bigan", max_length=250)),
                ("category", models.ManyToManyField(to="root.category")),
            ],
        ),
    ]
