# Generated by Django 4.2.5 on 2023-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
