# Generated by Django 4.2.5 on 2023-09-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_portfolio_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="ouner_category",
            field=models.ManyToManyField(
                related_name="portfolio_owner_category", to="root.category"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.ManyToManyField(
                related_name="portfolio_category", to="root.category"
            ),
        ),
    ]
